//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Orden
    {
        public Orden()
        {
            this.Reparacion = new HashSet<Reparacion>();
        }

        public int idOrden { get; set; }
        public int idPropietario { get; set; }
        public System.DateTime fechaIn { get; set; }
        public Nullable<System.DateTime> fechaOut { get; set; }
        [Required]
        [StringLength(8,MinimumLength = 1)]
        public string patente { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        public string detalleFalla { get; set; }
        public Nullable<double> total { get; set; }
        
        public string codigo { get; set; }
        [Required]
        [StringLength(20,MinimumLength=1)]
        public string marca { get; set; }

        public virtual Propietario Propietario { get; set; }
        public virtual ICollection<Reparacion> Reparacion { get; set; }
    }
}
