//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Propietario
    {
        public Propietario()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int idPropietario { get; set; }
        [StringLength(30,MinimumLength=1)]
        [Display(Name = "Nombre")]
        [Required]
        public string nombre { get; set; }
        [StringLength(30)]
        [Display(Name = "Apellido")]
        [Required]
        public string apellido { get; set; }
        [Display(Name = "Dni")]
        [Required]
        [Range(0,int.MaxValue)]
        public int dni { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Direccion de mail no valida")]
        [StringLength(50, ErrorMessage = "La cantaidad maxima es 50 caracteres")]
        public string mail { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [Range(1,9999999999)]
        public int telefono { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        public string direccion { get; set; }
        public string NombreApellido { get { return nombre + " " + apellido; } }
    
        public virtual ICollection<Orden> Orden { get; set; }
    }
}
