//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Repuesto
    {
        public Repuesto()
        {
            this.Reparacion = new HashSet<Reparacion>();
        }
    
        public int idRepuesto { get; set; }
        [Required]
        [StringLength(60)]
        public string nombre { get; set; }
        [Required]
        [Range(0,double.MaxValue)]
        public double costo { get; set; }
    
        public virtual ICollection<Reparacion> Reparacion { get; set; }
    }
}
