//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Reparacion = new HashSet<Reparacion>();
        }
    
        public int idUsuario { get; set; }
        public string userName { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string mail { get; set; }
        public int dni { get; set; }
        public string NombreApellido { get { return nombre + " " + apellido; } }
    
        public virtual ICollection<Reparacion> Reparacion { get; set; }
    }
}
